"""empty message

Revision ID: 76a8cd8e6c31
Revises: c53f6e45af2e
Create Date: 2018-04-22 17:16:11.226599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "76a8cd8e6c31"
down_revision = "c53f6e45af2e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questions", sa.Column("created", sa.DateTime(), nullable=True))
    op.add_column("questions", sa.Column("updated", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "updated")
    op.drop_column("questions", "created")
    # ### end Alembic commands ###
