"""empty message

Revision ID: d0f6afccf67b
Revises: 76a8cd8e6c31
Create Date: 2018-04-22 17:18:37.441646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0f6afccf67b'
down_revision = '76a8cd8e6c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('count_correct', sa.Integer(), nullable=True),
    sa.Column('count_incorrect', sa.Integer(), nullable=True),
    sa.Column('question_ids_snapshot', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('question_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
