"""empty message

Revision ID: f87bffe13c7a
Revises: d0f6afccf67b
Create Date: 2018-04-22 17:22:51.380526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f87bffe13c7a"
down_revision = "d0f6afccf67b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("created", sa.DateTime(), nullable=True))
    op.add_column("games", sa.Column("updated", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "updated")
    op.drop_column("games", "created")
    # ### end Alembic commands ###
